// Generated by CoffeeScript 1.12.7
(function() {
  var $comCloseButton, $comOpenButton, $sendButton, recieveCallback, sendCallback, serial, serialConfig;

  $comOpenButton = $('#com-open');
  $comCloseButton = $('#com-close');
  $sendButton = $('#send');
  $startButton = $('#start');
  $stopButton = $('#stop');
  
  $comOpenButton.click(function(event) {
    //ステータスを表示する
    document.getElementById("status").value = "OPEN";
    document.getElementById("com-open").disabled =true;
    document.getElementById("start").disabled=false;
    document.getElementById("stop").disabled =true;
    document.getElementById("com-close").disabled =false;
    serial.startConnection();
    return serial.startRecieve();
  });

  $comCloseButton.click(function(event) {
    //ステータスを表示する
    document.getElementById("status").value = "CLOSE";
    document.getElementById("com-open").disabled =false;
    document.getElementById("start").disabled=true;
    document.getElementById("stop").disabled =true;
    document.getElementById("com-close").disabled =true;
    return serial.endConnection();
  });

  $('#checkbox').on('change', function(event){
    serial.startConnection();
    return serial.startRecieve();
  });

  $sendButton.click(function(event) {
    return Green();
  });

  Green = function() {
    var message;
    console.log("target:"+document.getElementById("green").value);
    // 送信データを判断する
    target = document.getElementById("green").value
    if(target=="nvis"){
      message = ["0x82", "0x09", "0x22", "0x22", "0x22", "0x22",
                 document.getElementById("brightness").value, "0x0F", "0x0F", "0x0F", "0x00", "0x83", "0x00"];
    }else if(target=="avia"){
      message = ["0x82", "0x09", "0x11", "0x11", "0x11", "0x11",
                 document.getElementById("brightness").value, "0x0F", "0x0F", "0x0F", "0x00", "0x83", "0x00"];
    }else{
      console.log("!!!! NG !!!!");
    }
    console.log("textBox:" + message);
    return serial.sendData(message);
  };

  $startButton.click(function(event) {
    //ステータスを表示する
    document.getElementById("status").value = "Connected";
    document.getElementById("com-open").disabled =true;
    document.getElementById("start").disabled=true;
    document.getElementById("stop").disabled =false;
    document.getElementById("com-close").disabled =true;
    StartTimer();
  });

  $stopButton.click(function(event) {
    //ステータスを表示する
    document.getElementById("status").value = "Unconnected";
    document.getElementById("com-open").disabled =true;
    document.getElementById("start").disabled=false;
    document.getElementById("stop").disabled =true;
    document.getElementById("com-close").disabled =false;
    StopTimer();
  });

  recieveCallback = function(data) {
    console.log("recieve Callback");
    //テキストボックスに表示する
    document.getElementById("retun").value = data;
    //絵で表示する
    Disp();
    return console.log(data);
  };

  sendCallback = function(info) {
    console.log("send Callback");
  };

  serialConfig = {
    select: document.getElementById('ports'),
    bitrate: 115200,
    dataBits: "eight",
    parityBit: "odd",
    stopBits: "one",
    recieveCallback: recieveCallback,
    sendCallback: sendCallback
  };
  console.log(serialConfig);
  serial = new Serial(serialConfig);

}).call(this);

$(function(){

  
});